import cv2
import numpy as np
from typing import List
from app.services.reconstruction.optimization.edge_preservation import guided_filter

def refine_boundaries(
    reconstructed_bands: List[np.ndarray],
    mask: np.ndarray,
    kernel_size: int = 15
) -> List[np.ndarray]:
    """
    Feathers the transition seam between original clean pixels and reconstructed pixels
    by applying a guided edge-aware smoothing exactly at the mask boundary.
    
    Args:
        reconstructed_bands: Bands generated by reconstruction (list of 2D numpy arrays).
        mask: Reconstruction mask (2D array, values > 0 represent masked pixels).
        kernel_size: Base radius for guided filtering.
        
    Returns:
        List of 2D numpy arrays representing boundary-refined bands.
    """
    if kernel_size % 2 == 0:
        kernel_size += 1

    binary_mask = (mask > 0).astype(np.uint8) * 255
    
    # Generate the boundary zone (dilate and erode, then subtract)
    dilation_kernel = np.ones((5, 5), np.uint8)
    dilated = cv2.dilate(binary_mask, dilation_kernel, iterations=1)
    eroded = cv2.erode(binary_mask, dilation_kernel, iterations=1)
    boundary_mask = (dilated > 0) & (eroded == 0)
    
    # Create smooth baseline weight map for the boundary zone
    boundary_float = boundary_mask.astype(np.float32)
    alpha_base = cv2.GaussianBlur(boundary_float, (kernel_size, kernel_size), sigmaX=0)
    alpha_base = np.clip(alpha_base, 0.0, 1.0)
    
    refined_bands = []
    for band in reconstructed_bands:
        band_float = band.astype(np.float32)
        
        # Normalize the band to [0.0, 1.0] for guidance
        b_min, b_max = float(band_float.min()), float(band_float.max())
        if b_max > b_min:
            I = (band_float - b_min) / (b_max - b_min)
        else:
            I = np.zeros_like(band_float)
            
        # Refine feathering weight using guided filter (aligns transition with physical edges)
        r_val = max(1, kernel_size // 4)
        guided_alpha = guided_filter(I, alpha_base, r=r_val, eps=0.01)
        guided_alpha = np.clip(guided_alpha, 0.0, 1.0)
        
        # Apply edge-preserving smoothing inside the boundary zone
        smoothed = guided_filter(I, band_float, r=r_val, eps=0.02)
        
        # Blend the band with its smoothed version at the boundary using the guided weights
        blended = band_float * (1.0 - guided_alpha) + smoothed * guided_alpha
        refined_bands.append(blended.astype(band.dtype))
        
    return refined_bands
