import cv2
import numpy as np
from typing import List

def refine_boundaries(
    reconstructed_bands: List[np.ndarray],
    mask: np.ndarray,
    kernel_size: int = 15
) -> List[np.ndarray]:
    """
    Feathers the transition seam between original clean pixels and reconstructed pixels
    by applying a localized smoothing exactly at the mask boundary.
    
    Args:
        reconstructed_bands: Bands generated by Phase 7C reconstruction (list of 2D numpy arrays).
        mask: Reconstruction mask (2D array, values > 0 represent masked pixels).
        kernel_size: Gaussian kernel size for smoothing the boundary.
        
    Returns:
        List of 2D numpy arrays representing boundary-refined bands.
    """
    if kernel_size % 2 == 0:
        kernel_size += 1

    binary_mask = (mask > 0).astype(np.uint8) * 255
    
    # Generate the boundary zone (dilate and erode, then subtract)
    dilation_kernel = np.ones((5, 5), np.uint8)
    dilated = cv2.dilate(binary_mask, dilation_kernel, iterations=1)
    eroded = cv2.erode(binary_mask, dilation_kernel, iterations=1)
    boundary_mask = (dilated > 0) & (eroded == 0)
    
    # Create a smooth weight map for the boundary zone
    boundary_float = boundary_mask.astype(np.float32)
    alpha = cv2.GaussianBlur(boundary_float, (kernel_size, kernel_size), sigmaX=0)
    alpha = np.clip(alpha, 0.0, 1.0)
    
    refined_bands = []
    for band in reconstructed_bands:
        band_float = band.astype(np.float32)
        
        # Generate locally smoothed version of the band to eliminate sharp transitions
        smoothed = cv2.GaussianBlur(band_float, (kernel_size, kernel_size), sigmaX=0)
        
        # Blend the band with its smoothed version at the boundary
        blended = band_float * (1.0 - alpha) + smoothed * alpha
        refined_bands.append(blended.astype(band.dtype))
        
    return refined_bands
