import uuid
from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.core.database import Base

class TemporalFusionRun(Base):
    """
    SQLAlchemy Model representing a Temporal Fusion Run.
    Tracks lifecycle, status, strategy, and generated guidance summaries.
    """
    __tablename__ = "temporal_fusion_runs"

    id = Column(
        String,
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True,
        doc="Unique identifier for the temporal fusion run (UUIDv4 string)"
    )
    session_id = Column(
        String,
        ForeignKey("analysis_sessions.session_id", ondelete="CASCADE"),
        nullable=False,
        doc="Reference to the parent Analysis Session ID"
    )
    dataset_id = Column(
        String,
        ForeignKey("datasets.dataset_id", ondelete="CASCADE"),
        nullable=False,
        doc="Reference to the parent Dataset ID"
    )
    reconstruction_run_id = Column(
        String,
        ForeignKey("reconstruction_runs.id", ondelete="CASCADE"),
        nullable=False,
        doc="Reference to the parent Reconstruction Run ID"
    )
    fusion_status = Column(
        String,
        nullable=False,
        default="PENDING",
        doc="Lifecycle status: PENDING, RUNNING, COMPLETED, FAILED"
    )
    reference_count = Column(
        Integer,
        nullable=False,
        default=0,
        doc="Count of temporal reference images fused in this run"
    )
    fusion_strategy = Column(
        String,
        nullable=True,
        doc="Strategy used for temporal fusion"
    )
    guidance_summary = Column(
        Text,
        nullable=True,
        doc="Summary of reconstruction guidance generated by this run"
    )
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        doc="Timestamp when run was created"
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        doc="Timestamp of last update"
    )

    # Relationships
    session = relationship("AnalysisSession", back_populates="temporal_fusion_runs")
    dataset = relationship("Dataset", back_populates="temporal_fusion_runs")
    reconstruction_run = relationship("ReconstructionRun", back_populates="temporal_fusion_runs")
