import os
import datetime
from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional
from fpdf import FPDF


class BaseReportBuilder(ABC):
    """
    Abstract interface for report builders.
    Defines layout structure, decoupling data fetching from visualization format.
    """
    @abstractmethod
    def start_document(self, title: str, session_id: str) -> None:
        pass

    @abstractmethod
    def add_cover_page(self, report_type: str, dataset_name: str, session_id: str) -> None:
        pass

    @abstractmethod
    def add_section(self, title: str, grid_data: Dict[str, Any], text_block: Optional[str] = None) -> None:
        pass

    @abstractmethod
    def add_scorecard(self, title: str, grade: str, metrics: Dict[str, Any]) -> None:
        pass

    @abstractmethod
    def add_alert(self, title: str, message: str, level: str = "INFO") -> None:
        pass

    @abstractmethod
    def save_document(self, output_path: str) -> None:
        pass

class ScientificPDF(FPDF):
    """
    Custom FPDF subclass implementing scientific document headers, footers,
    and cover page accent styles.
    """
    def __init__(self, title_text: str = "", session_id: str = ""):
        super().__init__()
        self.title_text = title_text
        self.session_id = session_id

    def header(self):
        # Skip header on page 1 (cover page)
        if self.page_no() == 1:
            return
        
        self.set_font("Courier", "B", 8)
        self.set_text_color(71, 85, 105) # Slate-600
        header_text = f"ISRO LISS-IV EARTH OBSERVATION SYSTEMS  //  SESSION ID: {self.session_id.upper()}"
        self.cell(0, 5, header_text, border="B", ln=1, align="L")
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Courier", "I", 8)
        self.set_text_color(100, 116, 139) # Slate-500
        
        # Horizontal thin dividing line
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        self.cell(0, 10, f"GENERATED BY PLATFORM CORE: {timestamp}  |  STATUS: OPERATIONAL", align="L")
        self.set_x(-self.r_margin - 30)
        self.cell(30, 10, f"PAGE {self.page_no()}", align="R")

class PDFReportBuilder(BaseReportBuilder):
    """
    Concrete PDF report compiler using the fpdf2 library.
    Generates structured, print-ready, monospace scientific reports.
    """
    def __init__(self):
        self.pdf = None
        self.session_id = ""

    def start_document(self, title: str, session_id: str) -> None:
        self.session_id = session_id
        self.pdf = ScientificPDF(title_text=title, session_id=session_id)
        self.pdf.set_margins(15, 20, 15)
        self.pdf.set_auto_page_break(True, margin=20)

    def add_cover_page(self, report_type: str, dataset_name: str, session_id: str) -> None:
        if not self.pdf:
            raise RuntimeError("Document not started. Call start_document() first.")
        
        self.pdf.add_page()
        self.pdf.ln(20)

        # Draw a beautiful technical framing border
        self.pdf.set_line_width(0.8)
        self.pdf.set_draw_color(8, 145, 178) # Cyan-600
        self.pdf.rect(10, 10, self.pdf.w - 20, self.pdf.h - 20)

        # Science/ISRO telemetry theme branding
        self.pdf.set_font("Courier", "B", 14)
        self.pdf.set_text_color(15, 23, 42) # Slate-900
        self.pdf.cell(0, 10, "AI-POWERED GEOSPATIAL RECONSTRUCTION PLATFORM", ln=1, align="C")
        self.pdf.set_font("Courier", "I", 10)
        self.pdf.set_text_color(100, 116, 139)
        self.pdf.cell(0, 5, "LISS-IV COMPOSITE INPAINTING & DYNAMIC CORES", ln=1, align="C")
        self.pdf.ln(30)

        # Report Title
        self.pdf.set_font("Courier", "B", 20)
        self.pdf.set_text_color(8, 145, 178) # Cyan-600
        self.pdf.cell(0, 12, report_type.upper(), ln=1, align="C")
        self.pdf.ln(5)

        # Dividers
        self.pdf.set_line_width(1.5)
        self.pdf.line(40, self.pdf.get_y(), self.pdf.w - 40, self.pdf.get_y())
        self.pdf.ln(20)

        # Technical Info Block
        self.pdf.set_font("Courier", "B", 10)
        self.pdf.set_text_color(15, 23, 42)
        
        # Cover table metadata values
        meta_items = [
            ("ACQUISITION SESSION ID", session_id),
            ("LOCK TARGET DATASET", dataset_name),
            ("GENERATION TIMESTAMP", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")),
            ("SECURITY REGISTRY CODE", "ISRO-BAH26-PROD-MC"),
            ("SYSTEM READINESS LEVEL", "OPERATIONAL STATUS OK"),
        ]

        # Draw a beautiful key-value grid for metadata
        box_width = 140
        box_x = (self.pdf.w - box_width) / 2
        self.pdf.set_x(box_x)

        # Draw thin bounding box
        y_start = self.pdf.get_y()
        self.pdf.set_draw_color(203, 213, 225) # Slate-200
        self.pdf.set_fill_color(248, 250, 252) # Slate-50
        self.pdf.rect(box_x, y_start, box_width, len(meta_items) * 8 + 4, style="FD")
        
        self.pdf.set_y(y_start + 2)
        for label, val in meta_items:
            self.pdf.set_x(box_x + 4)
            self.pdf.set_font("Courier", "B", 9)
            self.pdf.set_text_color(71, 85, 105)
            self.pdf.cell(50, 8, label.ljust(25) + ":")
            self.pdf.set_font("Courier", "", 9)
            self.pdf.set_text_color(15, 23, 42)
            self.pdf.cell(80, 8, str(val), ln=1)

        self.pdf.ln(35)
        
        # Add cover graphics/branding notes
        self.pdf.set_font("Courier", "I", 7.5)
        self.pdf.set_text_color(148, 163, 184)
        self.pdf.cell(0, 5, "CONFIDENTIALITY NOTICE: This report contains operational earth telemetry details.", ln=1, align="C")
        self.pdf.cell(0, 4, "Prepared exclusively for scientific research, analysis, and operations validation.", ln=1, align="C")

    def add_section(self, title: str, grid_data: Dict[str, Any], text_block: Optional[str] = None) -> None:
        if not self.pdf:
            raise RuntimeError("Document not started.")

        self.pdf.ln(8)
        self.pdf.set_font("Courier", "B", 12)
        self.pdf.set_text_color(15, 23, 42)
        self.pdf.cell(0, 8, f"// {title.upper()}", border="B", ln=1)
        self.pdf.ln(4)

        if grid_data:
            # Draw scientific table grid layout
            self.pdf.set_font("Courier", "B", 9)
            self.pdf.set_text_color(71, 85, 105)
            
            # Format keys & values as columns
            col_width = (self.pdf.w - self.pdf.l_margin - self.pdf.r_margin) / 2
            
            items = list(grid_data.items())
            for i in range(0, len(items), 2):
                # Row content
                k1, v1 = items[i]
                has_next = (i + 1) < len(items)
                k2, v2 = items[i+1] if has_next else ("", "")

                # Cell 1
                self.pdf.set_font("Courier", "B", 8.5)
                self.pdf.set_text_color(100, 116, 139)
                self.pdf.cell(col_width * 0.45, 6, str(k1).upper() + ":", align="L")
                self.pdf.set_font("Courier", "", 8.5)
                self.pdf.set_text_color(15, 23, 42)
                self.pdf.cell(col_width * 0.55, 6, str(v1), align="L")

                if has_next:
                    # Cell 2
                    self.pdf.set_font("Courier", "B", 8.5)
                    self.pdf.set_text_color(100, 116, 139)
                    self.pdf.cell(col_width * 0.45, 6, str(k2).upper() + ":", align="L")
                    self.pdf.set_font("Courier", "", 8.5)
                    self.pdf.set_text_color(15, 23, 42)
                    self.pdf.cell(col_width * 0.55, 6, str(v2), ln=1, align="L")
                else:
                    self.pdf.ln(6)

        if text_block:
            self.pdf.ln(2)
            self.pdf.set_font("Courier", "", 9)
            self.pdf.set_text_color(51, 65, 85) # Slate-700
            self.pdf.multi_cell(0, 5, text_block)
            self.pdf.ln(2)

    def add_scorecard(self, title: str, grade: str, metrics: Dict[str, Any]) -> None:
        if not self.pdf:
            raise RuntimeError("Document not started.")

        self.pdf.ln(8)
        self.pdf.set_font("Courier", "B", 12)
        self.pdf.set_text_color(15, 23, 42)
        self.pdf.cell(0, 8, f"// {title.upper()}", border="B", ln=1)
        self.pdf.ln(4)

        # Draw a highlighted scorecard panel
        self.pdf.set_draw_color(8, 145, 178) # Cyan-600
        self.pdf.set_fill_color(236, 254, 255) # Cyan-50
        box_y = self.pdf.get_y()
        self.pdf.rect(self.pdf.l_margin, box_y, self.pdf.w - self.pdf.l_margin - self.pdf.r_margin, 25, style="FD")

        # Grade Circle Block
        self.pdf.set_x(self.pdf.l_margin + 5)
        self.pdf.set_y(box_y + 4)
        self.pdf.set_font("Courier", "B", 24)
        self.pdf.set_text_color(8, 145, 178)
        self.pdf.cell(30, 18, f" {grade}", border=1, align="C")

        # Metrics lists
        self.pdf.set_y(box_y + 3)
        self.pdf.set_x(self.pdf.l_margin + 42)
        self.pdf.set_font("Courier", "B", 9)
        self.pdf.set_text_color(71, 85, 105)
        
        # Format keys
        idx = 0
        for label, val in metrics.items():
            self.pdf.set_x(self.pdf.l_margin + 42)
            self.pdf.set_font("Courier", "B", 8)
            self.pdf.set_text_color(71, 85, 105)
            self.pdf.cell(50, 4.5, str(label).upper() + ":")
            self.pdf.set_font("Courier", "B", 8.5)
            self.pdf.set_text_color(15, 23, 42)
            self.pdf.cell(40, 4.5, str(val), ln=1)
            idx += 1

        self.pdf.set_y(box_y + 25)
        self.pdf.ln(4)

    def add_alert(self, title: str, message: str, level: str = "INFO") -> None:
        if not self.pdf:
            raise RuntimeError("Document not started.")

        self.pdf.ln(4)
        if level == "WARNING" or level == "CRITICAL":
            self.pdf.set_draw_color(220, 38, 38) # Red-600
            self.pdf.set_fill_color(254, 242, 242) # Red-50
            self.pdf.set_text_color(220, 38, 38)
        else:
            self.pdf.set_draw_color(202, 138, 4) # Yellow-600
            self.pdf.set_fill_color(254, 252, 232) # Yellow-50
            self.pdf.set_text_color(161, 98, 7)

        box_y = self.pdf.get_y()
        self.pdf.rect(self.pdf.l_margin, box_y, self.pdf.w - self.pdf.l_margin - self.pdf.r_margin, 15, style="FD")
        
        self.pdf.set_y(box_y + 2)
        self.pdf.set_x(self.pdf.l_margin + 4)
        self.pdf.set_font("Courier", "B", 9)
        self.pdf.cell(0, 5, f"[{level}] {title}: {message}", ln=1)
        self.pdf.ln(4)

    def save_document(self, output_path: str) -> None:
        if not self.pdf:
            raise RuntimeError("Document not compile-ready.")
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        self.pdf.output(output_path)
