import sys
import os

# Add backend directory to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "backend")))

# Configure test database
db_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "test_phase_3b.db"))
os.environ["SQLALCHEMY_DATABASE_URL"] = f"sqlite:///{db_path.replace(os.sep, '/')}"

from fastapi.testclient import TestClient
from app.main import app
from app.core.database import init_db

print("Starting Phase 3B Location Intelligence API Verification...")
init_db()

client = TestClient(app)

def print_header(title):
    print(f"\n==================================================")
    print(f" {title}")
    print(f"==================================================")

try:
    # 1. Create session
    print_header("1. Create Analysis Session")
    r = client.post("/api/v1/analysis")
    assert r.status_code == 201, f"Expected 201, got {r.status_code}"
    session = r.json()
    session_id = session["session_id"]
    print(f"Session created with ID: {session_id}")

    # 2. Discover demo datasets
    print_header("2. Discover Demo Datasets")
    r = client.get("/api/v1/datasets/demo")
    assert r.status_code == 200, f"Expected 200, got {r.status_code}"
    demo_datasets = r.json()
    assert len(demo_datasets) > 0, "No demo datasets discovered!"
    
    # Target dataset: R2F12AUG2025074282009600051SSANSTUC00GTDD
    target_ds = None
    for ds in demo_datasets:
        if ds["dataset_name"] == "R2F12AUG2025074282009600051SSANSTUC00GTDD":
            target_ds = ds
            break
    
    if not target_ds:
        target_ds = demo_datasets[0]
        
    print(f"Selected target dataset: {target_ds['dataset_name']}")

    # 3. Register dataset
    print_header("3. Register Dataset under Session")
    register_payload = {
        "analysis_session_id": session_id,
        "dataset_name": target_ds["dataset_name"],
        "dataset_path": target_ds["dataset_path"],
        "dataset_type": target_ds["dataset_type"]
    }
    r = client.post("/api/v1/datasets/register", json=register_payload)
    assert r.status_code == 201, f"Expected 201, got {r.status_code}"
    registered = r.json()
    dataset_id = registered["dataset_id"]
    print(f"Registered Dataset ID: {dataset_id}")

    # 4. Run dataset inspection
    print_header("4. Run Dataset Inspection")
    r = client.post(f"/api/v1/dataset-inspection/run/{dataset_id}")
    assert r.status_code == 200, f"Expected 200, got {r.status_code}"
    print("Inspection Completed.")

    # 5. Run metadata extraction
    print_header("5. Run Metadata Extraction")
    r = client.post(f"/api/v1/dataset-metadata/run/{dataset_id}")
    assert r.status_code == 200, f"Expected 200, got {r.status_code}"
    print("Metadata extraction completed.")

    # 6. Retrieve Location Context
    # NOTE: This should automatically trigger lazy generation of Geospatial Context since we haven't run it yet!
    print_header("6. Retrieve Location Context (First Calculation & Lazy Coordinates Cascade)")
    r = client.get(f"/api/v1/location/{dataset_id}/context")
    assert r.status_code == 200, f"Expected 200, got {r.status_code}"
    location = r.json()
    print("Location Profile Generated:")
    print(location)

    # Assert structural compliance
    assert location["dataset_id"] == dataset_id
    assert location["country"].strip() != ""
    assert location["state"].strip() != ""
    assert location["district"].strip() != ""
    assert location["administrative_region"].strip() != ""
    assert location["geographic_region"].strip() != ""
    assert location["location_summary"].strip() != ""
    
    # Assert values match resolved coordinates for Bulandshahr / UP
    # Nominatim or offline local might be used, but either should resolve country=India, state=Uttar Pradesh, district=Bulandshahr/Mathura/Central Zone
    assert "india" in location["country"].lower()
    assert "uttar pradesh" in location["state"].lower()
    assert location["administrative_region"] == "Northern India"
    assert location["geographic_region"] == "Indo-Gangetic Plain"
    assert "indo-gangetic plain" in location["location_summary"].lower()
    assert "uttar pradesh" in location["location_summary"].lower()
    
    print("Location Intelligence profile parameters verified.")

    # 7. Check that Geospatial Context was lazily created under-the-hood
    print_header("7. Check Lazy Geospatial Context Generation Verification")
    r = client.get(f"/api/v1/geospatial/{dataset_id}/context")
    assert r.status_code == 200, f"Expected 200, got {r.status_code}"
    geospatial = r.json()
    assert geospatial["epsg"] == 32643
    print("Success: Geospatial context was successfully generated by the location lazy-loader cascade.")

    # 8. Retrieve Location Context again (Read from DB Check)
    print_header("8. Retrieve Location Context Again (Database Cache Check)")
    r = client.get(f"/api/v1/location/{dataset_id}/context")
    assert r.status_code == 200
    cache_location = r.json()
    assert cache_location["location_summary"] == location["location_summary"]
    print("Database retrieval cache verification passed.")

    # 9. Delete dataset registration (Verify cascading deletion of location context)
    print_header("9. Delete Dataset & Verify Location Context Cascade")
    r = client.delete(f"/api/v1/datasets/{dataset_id}")
    assert r.status_code == 204, f"Expected 204, got {r.status_code}"
    
    # Try retrieving location context now - should be 404 because dataset doesn't exist
    r = client.get(f"/api/v1/location/{dataset_id}/context")
    assert r.status_code == 404, f"Expected 404 on deleted dataset, got {r.status_code}"
    print("Success: Dataset delete cascaded to delete database LocationContext record.")

    print("\n==================================================")
    print(" ALL PHASE 3B LOCATION INTELLIGENCE VERIFICATIONS PASSED!")
    print("==================================================")

except Exception as e:
    print(f"\nValidation failed with error: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

finally:
    if os.path.exists(db_path):
        try:
            os.remove(db_path)
            print("\nCleanup: Test database file deleted.")
        except Exception as e:
            print(f"\nCleanup warning: Could not remove test database file: {e}")
